<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdministrativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministrativoRepository extends EntityRepository
{
	public function todos($administrativo)
	{
		return $this->getEntityManager()->createQuery('SELECT e FROM AppBundle:Administrativo e WHERE e.usuario = :usuario')->setParameter('usuario',$administrativo)->getResult();
	}
}
